import type { AgentRole, CompanyRow, OverviewPayload, RunSummary } from "@/lib/types";

const AGENTS: AgentRole[] = [
  {
    key: "identity",
    label: "Legal entity resolver",
    layer: "Identity",
    engine: "human",
    summary: "Binds the case to one exact Companies House number under a named decision.",
    owns: "Exact identifiers, reviewed aliases and verified first-party domains.",
    must_not: "Merge on a name, a filename or a domain that no reviewer has accepted.",
    inputs: "Submitted identifier claim and reviewer rationale.",
    outputs: "Accepted or rejected identifier; the case stays held until accepted.",
  },
  {
    key: "discover_sources",
    label: "Source planner",
    layer: "Planning",
    engine: "model",
    summary: "Asks the external model for candidate public source URLs. It records URLs only.",
    owns: "The candidate source set for this run.",
    must_not: "Invent identifiers or parse page content into claims.",
    inputs: "Company number, canonical name, reporting cutoff, pinned budgets.",
    outputs: "Discovered source rows with publisher domain and source tier.",
  },
  {
    key: "capture_sources",
    label: "Safe public fetcher",
    layer: "Acquisition",
    engine: "deterministic",
    summary: "Fetches each candidate over a DNS-pinned, robots-aware transport.",
    owns: "Raw bytes, SHA-256 checksums, HTTP status and per-source terminal state.",
    must_not: "Follow instructions found in a page, or store an unredacted snapshot.",
    inputs: "Discovered source URLs and the run's pinned transport budgets.",
    outputs: "Fetched, blocked, unsupported or failed state for every candidate.",
  },
  {
    key: "extract_claims",
    label: "Claim extractor and span validator",
    layer: "Extraction",
    engine: "model",
    summary: "The model proposes claims; code admits only verbatim snapshot spans.",
    owns: "Admitted claims, their exact evidence span and their source locator.",
    must_not: "Admit a paraphrase, a post-cutoff event or a recommendation.",
    inputs: "Redacted snapshot text, checksum-verified against the stored bytes.",
    outputs: "Claims carrying category, perspective, span and source linkage.",
  },
  {
    key: "compose_deck",
    label: "Profile composer",
    layer: "Synthesis",
    engine: "deterministic",
    summary: "Groups admitted claims into profile sections and hashes the result.",
    owns: "The versioned company profile and its contradiction ledger.",
    must_not: "Add a sentence that is not an admitted claim.",
    inputs: "Admitted claims and captured source records for this run only.",
    outputs: "One pending-review profile version with a content checksum.",
  },
  {
    key: "human_review",
    label: "Named reviewer",
    layer: "Human",
    engine: "human",
    summary: "The only role that can approve a cited profile version.",
    owns: "Approve and reject authority.",
    must_not: "Alter immutable evidence or a recorded verification outcome.",
    inputs: "The pending profile version and its expected lock version.",
    outputs: "An audited approval or rejection with a written rationale.",
  },
];

function company(
  partial: Partial<CompanyRow> & Pick<CompanyRow, "id" | "name">,
): CompanyRow {
  return {
    entity_type: "ltd",
    jurisdiction: "GB",
    lifecycle_status: "active",
    resolution_status: "resolved",
    classification: "public_research",
    created_at: "2026-08-12T09:00:00Z",
    identifier: {
      id: `${partial.id}-ch`,
      scheme: "companies_house",
      value: "00000000",
      state: "accepted",
    },
    verified_domain: null,
    open_decisions: 0,
    case_id: `${partial.id}-case`,
    case_count: 1,
    artifact_count: 0,
    claim_count: 0,
    run_count: 1,
    latest_run: null,
    next_action: { label: "Open company", detail: "", href: `/companies/${partial.id}` },
    ...partial,
  };
}

function run(partial: Partial<RunSummary> & Pick<RunSummary, "id" | "company_id" | "company_name" | "status">): RunSummary {
  return {
    cutoff: "2026-08-31",
    created_at: "2026-09-01T10:00:00Z",
    updated_at: "2026-09-01T11:20:00Z",
    model: "gpt-5.4-mini",
    source_policy_version: "source-policy-1",
    stages_total: 4,
    stages_done: 1,
    active_capability: "capture_sources",
    active_role: "Safe public fetcher",
    claim_count: 0,
    sources: { total: 8, discovered: 8, fetched: 3, blocked: 0, unsupported: 0, failed: 0 },
    error_code: null,
    profile: null,
    ...partial,
  };
}

/** Static Overview fixture. Used only by `/mock` so the layout can be judged without the API. */
export const OVERVIEW_MOCK: OverviewPayload = {
  live_research_enabled: true,
  next_action: {
    label: "Resolve 2 identity hold(s)",
    detail: "Nothing collects evidence until the exact legal entity is accepted.",
    href: "/companies",
  },
  metrics: {
    companies: 4,
    resolved: 2,
    identity_holds: 2,
    runs_total: 4,
    runs_active: 1,
    runs_pending_review: 1,
    claims: 38,
    sources_captured: 19,
    sources_withheld: 3,
  },
  system: {
    reviewer: "A. Chen",
    reviewer_configured: true,
    live_research_enabled: true,
    research_mode: "live",
    external_model_enabled: true,
    live_retrieval_enabled: true,
    model: "gpt-5.4-mini",
    escalation_model: "gpt-5.4",
    runtime: "Loopback only · synchronous · SQLite",
    boundary:
      "Bounded public research is live. Sources are retrieved over a DNS-pinned, robots-aware transport and snapshotted before parsing.",
    model_route: {
      reasoning: { model: "gpt-5.4", effort: "high", stages: ["discover_sources"] },
      selection: { model: "gpt-5.4-mini", effort: "high", stages: ["extract_claims"] },
      repair: { model: "gpt-5.4-mini", effort: "high", when: "any repeat attempt after a rejected result" },
    },
    budgets: {
      max_sources: 12,
      max_tool_calls: 16,
      timeout_seconds: 20,
    },
    agents: AGENTS,
  },
  attention: [
    {
      id: "failed-run-3",
      kind: "Failure",
      severity: "danger",
      title: "Example Industries Ltd",
      detail: "Stage failure recorded: source_fetch_timeout.",
      action_label: "Inspect run",
      href: "/runs/run-3",
    },
    {
      id: "identity-co-2",
      kind: "Identity",
      severity: "hold",
      title: "Northbridge Analytics Ltd",
      detail: "2 unreviewed identity claim(s).",
      action_label: "Open company",
      href: "/companies/co-2",
    },
    {
      id: "review-run-2",
      kind: "Review",
      severity: "review",
      title: "Monq Ltd",
      detail: "A cited profile version awaits a named decision.",
      action_label: "Open run",
      href: "/runs/run-2",
    },
    {
      id: "active-run-1",
      kind: "Execution",
      severity: "active",
      title: "Acme Research Ltd",
      detail: "1/4 stages complete · next: Safe public fetcher",
      action_label: "Open run",
      href: "/runs/run-1",
    },
    {
      id: "sources-run-3",
      kind: "Coverage",
      severity: "warning",
      title: "Example Industries Ltd",
      detail: "3 source(s) blocked or failed and are absent from evidence.",
      action_label: "Open run",
      href: "/runs/run-3",
    },
  ],
  runs: [
    run({
      id: "run-1",
      company_id: "co-1",
      company_name: "Acme Research Ltd",
      status: "running",
      stages_done: 1,
      active_capability: "capture_sources",
      active_role: "Safe public fetcher",
      sources: { total: 8, fetched: 3, blocked: 0, failed: 0, unsupported: 0 },
      claim_count: 0,
    }),
    run({
      id: "run-2",
      company_id: "co-3",
      company_name: "Monq Ltd",
      status: "pending_review",
      stages_done: 4,
      active_capability: null,
      active_role: "Named reviewer",
      sources: { total: 10, fetched: 9, blocked: 1, failed: 0, unsupported: 0 },
      claim_count: 22,
      profile: { id: "pv-2", version: 1, status: "pending_review", content_sha256: "aaa" },
    }),
    run({
      id: "run-3",
      company_id: "co-4",
      company_name: "Example Industries Ltd",
      status: "failed",
      stages_done: 1,
      active_capability: "capture_sources",
      active_role: "Safe public fetcher",
      sources: { total: 8, fetched: 2, blocked: 1, failed: 2, unsupported: 0 },
      error_code: "source_fetch_timeout",
      claim_count: 0,
    }),
    run({
      id: "run-4",
      company_id: "co-5",
      company_name: "Widget Holdings Ltd",
      status: "approved",
      stages_done: 4,
      active_capability: null,
      active_role: null,
      sources: { total: 7, fetched: 5, blocked: 0, failed: 0, unsupported: 0 },
      claim_count: 16,
      profile: { id: "pv-4", version: 1, status: "approved", content_sha256: "bbb" },
    }),
    run({
      id: "run-5",
      company_id: "co-6",
      company_name: "Harbour Light Energy Ltd",
      status: "approved",
      cutoff: "2026-06-30",
      stages_done: 4,
      active_capability: null,
      active_role: null,
      sources: { total: 11, fetched: 10, blocked: 0, failed: 0, unsupported: 1 },
      claim_count: 31,
      profile: {
        id: "pv-5",
        version: 2,
        status: "approved",
        content_sha256: "c1f4e8d2a90b77aa0012",
      },
    }),
  ],
  companies: [
    company({
      id: "co-2",
      name: "Northbridge Analytics Ltd",
      resolution_status: "identity_hold",
      open_decisions: 2,
      identifier: { id: "co-2-ch", scheme: "companies_house", value: "14882201", state: "pending" },
      claim_count: 0,
      run_count: 0,
      next_action: { label: "Accept identity", detail: "", href: "/companies/co-2" },
    }),
    company({
      id: "co-1",
      name: "Acme Research Ltd",
      identifier: { id: "co-1-ch", scheme: "companies_house", value: "12345678", state: "accepted" },
      claim_count: 0,
      latest_run: { id: "run-1", status: "running", cutoff: "2026-08-31", created_at: "2026-09-01T10:00:00Z" },
      next_action: { label: "Advance run", detail: "", href: "/runs/run-1" },
    }),
    company({
      id: "co-3",
      name: "Monq Ltd",
      identifier: { id: "co-3-ch", scheme: "companies_house", value: "11223344", state: "accepted" },
      claim_count: 22,
      latest_run: { id: "run-2", status: "pending_review", cutoff: "2026-08-31", created_at: "2026-08-29T16:00:00Z" },
      next_action: { label: "Review profile", detail: "", href: "/runs/run-2" },
    }),
    company({
      id: "co-4",
      name: "Example Industries Ltd",
      identifier: { id: "co-4-ch", scheme: "companies_house", value: "00998877", state: "accepted" },
      claim_count: 0,
      latest_run: { id: "run-3", status: "failed", cutoff: "2026-08-31", created_at: "2026-08-28T09:00:00Z" },
      next_action: { label: "Inspect failure", detail: "", href: "/runs/run-3" },
    }),
  ],
};
